name: JuicyPixels-scale-dct
version: 0.1.1.0
synopsis: Scale JuicyPixels images with DCT
description: Scale JuicyPixels Images with DCT
author: Oleg Grenrus <oleg.grenrus@iki.fi>
maintainer: Oleg Grenrus <oleg.grenrus@iki.fi>
license: BSD3
github: phadej/JuicyPixels-scale-dct
category: Web
tested-with: GHC==7.8.4, GHC==7.10.3, GHC==8.0.1
extra-source-files:
- README.md
- CHANGELOG.md
- phadej.png

ghc-options: -Wall

dependencies:
  - base        >=4.7      && <4.10
  - base-compat >=0.6.0    && <0.10
  - JuicyPixels >=3.2.5.3  && <3.3
  - fft         >=0.1.8.1  && <0.2
  - carray      >=0.1.6.1  && <0.2

library:
  source-dirs: src

tests:
  example:
    main: Example.hs
    source-dirs: example
    dependencies:
      - base
      - JuicyPixels
      - JuicyPixels-scale-dct
      - JuicyPixels-util      >=0.2   && <0.3
      - time                  >=1.4.2 && <1.7
